### ISSUE TITLE
Satisfactory v1.0 Port Change

### ISSUE THREAD

**Issue by generalrap** [DJWoodZ/satisfactory-dedicated-server-query-port-probe#1]
Satisfactory's v1.0 update deprecates port 15777, and only utilizes port 7777. Can this probe be changed to reflect that update?

**Comment by DJWoodZ** [comment]
This library should allow you to specify a different port. However, I think the real issue is that Satisfactory 1.0 works differently to the previous version and this library no longer works because of that. I will investigate.

**Comment by generalrap** [comment]
That makes sense. I attempted to fork this locally and change the port, but wasn't having any luck. You probably have much more insight as to how the Satisfactory logs work than I do however.

**Comment by DJWoodZ** [comment]
This library will be deprecated in favour of [DJWoodZ/satisfactory-dedicated-server-lightweight-query-probe](/DJWoodZ/satisfactory-dedicated-server-lightweight-query-probe). Please see [DJWoodZ/Satisfactory-Discord-Bot/issues/33](/DJWoodZ/Satisfactory-Discord-Bot/issues/33) for details.
